name: ML Pipeline - Notebook Execution
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  execute-notebooks:
    name: Execute Notebooks in Sequence
    runs-on: ubuntu-latest
    timeout-minutes: 45  # Aumentado para MLflow y procesamiento de datos

    steps:
    # Paso 1: Checkout del código
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Paso 2: Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Paso 3: Instalar dependencias completas
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install notebook nbconvert papermill
        pip install pandas scikit-learn matplotlib seaborn
        pip install mlflow gdown pyngrok joblib
        pip install ipykernel
        sudo apt-get update && sudo apt-get install -y unzip

    # Paso 4: Crear estructura de directorios
    - name: Create Directories
      run: |
        mkdir -p data
        mkdir -p mlruns
        mkdir -p output

    # Paso 5: Ejecutar notebooks en orden con manejo de errores
    - name: Run Exploratory Analysis
      run: |
        echo "Ejecutando Analisis_exploratorio.ipynb..."
        jupyter nbconvert --execute --to notebook --inplace Analisis_exploratorio.ipynb || exit 1
        jupyter nbconvert --to html Analisis_exploratorio.ipynb

    - name: Run Preprocessing
      run: |
        echo "Ejecutando Preprocesamiento.ipynb..."
        jupyter nbconvert --execute --to notebook --inplace Preprocesamiento.ipynb || exit 1
        jupyter nbconvert --to html Preprocesamiento.ipynb

    - name: Run Feature Selection
      run: |
        echo "Ejecutando Entrenamiento_y_validación_del_modelo.ipynb..."
        jupyter nbconvert --execute --to notebook --inplace Entrenamiento_y_validación_del_modelo.ipynb || exit 1
        jupyter nbconvert --to html Entrenamiento_y_validación_del_modelo.ipynb

    - name: Run Model Training
      run: |
        echo "Ejecutando Evaluación_final_y_exportacion.ipynb..."
        jupyter nbconvert --execute --to notebook --inplace Evaluación_final_y_exportacion.ipynb || exit 1
        jupyter nbconvert --to html Evaluación_final_y_exportacion.ipynb
        # Iniciar MLflow UI en background (solo para debugging)
        nohup mlflow ui --port 5000 --host 0.0.0.0 &

    # Paso 6: Subir resultados como artefactos
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: ml-pipeline-results
        path: |
          *.html
          *.pkl
          *.csv
          mlruns/
          output/
          data/processed_*
        retention-days: 2

    # Paso opcional: Subir HTML para visualización
    - name: Upload Notebooks as HTML
      uses: actions/upload-artifact@v4
      with:
        name: notebooks-html
        path: |
          *.html
        retention-days: 1
